// DECK FORM
export const DECK_MERGE_INPUT = 'DECK_MERGE_INPUT'
export const DECK_CLEAN_FORM = 'DECK_CLEAN_FORM'

// CARD FORM

export const CARD_MERGE_INPUT = 'CARD_MERGE_INPUT'
export const CARD_CLEAN_FORM = 'CARD_CLEAN_FORM'